spring:
  application:
    name: board # 프로젝트 이름
  datasource: # 데이터베이스 접속정보
    url: jdbc:mysql://localhost:3306/board
    username: root
    password: green502

mybatis: # Mybatis 세팅
  mapper-locations: mappers/**/*.xml # xml 파일 위치